default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: 'postgres://postgres:postgres@localhost:5432/mediapp_development'

test:
  <<: *default
  url: 'postgres://postgres:postgres@localhost:5432/mediapp_test'

production:
  <<: *default
  url: <%= Rails.application.credentials['DB_URL'] %>
